let data;
const node=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
function jump(side,id){const doc=document.getElementById(side).contentDocument;if(!doc)return;doc.querySelectorAll('.lab-selected').forEach(t=>t.classList.remove('lab-selected'));const table=doc.getElementById('lab-table-'+id);if(table){table.classList.add('lab-selected');table.scrollIntoView({block:'start'});}}
function rowInfo(c){return `${c.scope} · ${c.role} · ${c.period} · ${c.unit}\n`+c.rows.map(row=>row.join(' | ')).join('\n');}
async function load(){const button=document.getElementById('reload');button.disabled=true;try{data=await window.lab.analyze();const results=document.getElementById('results');results.replaceChildren();if(data.error){document.getElementById('summary').textContent=data.error;return;}
 document.getElementById('summary').textContent=`유형자산 감가상각 표 ${data.left.candidates.length} / ${data.right.candidates.length}개 · 대응 ${data.pairs.length}쌍`;
 for(const side of ['left','right'])document.getElementById(side).srcdoc=data[side].html;
 results.append(node('p',`전체 표 ${data.left.tableCount} / ${data.right.tableCount}개. 유형자산 밖 감가상각 표 ${data.left.rejected.length} / ${data.right.rejected.length}개 제외.`));
 for(const p of data.pairs){const a=data.left.candidates.find(c=>c.id===p.left),b=data.right.candidates.find(c=>c.id===p.right),card=node('article','');card.append(node('h3',`${a.period} · ${a.scope}`),node('p',`매칭 점수 ${p.evidence.score} · ${p.evidence.reasons.join(' / ')}`),node('pre','2023: '+rowInfo(a)+'\n\n2022: '+rowInfo(b)));const show=node('button','양쪽 원문으로 이동');show.onclick=()=>{jump('left',a.id);jump('right',b.id);};card.append(show);const status=node('span',' 미검수');for(const verdict of ['합격','불합격']){const btn=node('button',verdict);btn.onclick=()=>status.textContent=' '+verdict;card.append(btn);}card.append(status,node('details',''));const details=card.querySelector('details');details.append(node('summary','구간·주변 문맥 확인'),node('p',a.section+' → '+a.boundary+'\n'+a.context),node('p',b.section+' → '+b.boundary+'\n'+b.context));results.append(card);}
 for(const [side,ids]of [['left',data.unmatchedLeft],['right',data.unmatchedRight]])for(const id of ids){const c=data[side].candidates.find(c=>c.id===id),card=node('article',`${data[side].label}: 대응 미확정\n${rowInfo(c)}`),btn=node('button','이 표 보기');btn.onclick=()=>jump(side,id);card.append(btn);results.append(card);}
 }catch(e){document.getElementById('summary').textContent=e.message;}finally{button.disabled=false;}}
document.getElementById('reload').onclick=load;load();
